### PR TITLE
Fix #180

### LINKED ISSUE #180: Wrong value selected on keypress
Selects wrong value on keypress. Experienced on latest version v1.11.1. On demo page version ( v1.11.0) all works as expected.

Example: 
<select>
<option value="aa">AA</option>
<option value="ab">AB</option>
<option value="ac">AC</option>
</select>
If you press key "a" - expected the first value "AA" to be selected not the last one "AC" as it is on version v1.11.1

### PR DESCRIPTION
**Pull request by Epiphero**
As per the [jQuery docs](http://api.jquery.com/jquery.each/), returning false from the each callback will stop the loop.  That way the 1st matching element will be highlighted, not the last.  This should resolve #180.

### CODE REVIEW

**Comment by gearsdigital** [comment]
Thank you very much for your PR. Glad you fixed that issue!

Before the is going to be merged could please provide a test case?

Regards!

**Comment by Epiphero** [comment]
@gearsdigital Sure thing: I committed two tests, one for each of the changed code paths.

**Comment by gearsdigital** [comment]
Awesome! :) I'll test and verfiy it later this day…

**Comment by Kamyil** [comment]
Not sure whever this library is still maintained or not but... wondering why this PR was not released? 
It's definitely fixing the issue, however while using Selectric 1.13.0 from npm it does not appear to have this change

**Pull request merged**
